// <auto-generated />
using System;
using Comssire.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Comssire.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260216165755_ActModuloCompras")]
    partial class ActModuloCompras
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Comssire.Models.Compras.Compra", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AprobadoAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("AprobadoPorUserId")
                        .HasColumnType("integer");

                    b.Property<int>("CreadoPorUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CveClpv")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime?>("EnviadoAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EnviadoPorUserId")
                        .HasColumnType("integer");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FolioFactura")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int?>("ModConsecutivo")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ModGeneradoAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MotivoRechazo")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<int>("NumAlmaDefault")
                        .HasColumnType("integer");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("RechazadoAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("RechazadoPorUserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AprobadoPorUserId");

                    b.HasIndex("CreadoPorUserId");

                    b.HasIndex("EnviadoPorUserId");

                    b.HasIndex("Estado");

                    b.HasIndex("Fecha");

                    b.HasIndex("RechazadoPorUserId");

                    b.HasIndex("CveClpv", "FolioFactura")
                        .IsUnique();

                    b.ToTable("Compras");
                });

            modelBuilder.Entity("Comssire.Models.Compras.CompraPartida", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("CantTotal")
                        .HasColumnType("numeric");

                    b.Property<Guid>("CompraId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("CostoUnitario")
                        .HasColumnType("numeric");

                    b.Property<string>("CveArt")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("IvaPct")
                        .HasColumnType("numeric");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("UniVenta")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasIndex("CompraId");

                    b.HasIndex("CveArt");

                    b.ToTable("CompraPartidas");
                });

            modelBuilder.Entity("Comssire.Models.Compras.CompraPartidaAlmacen", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Cant")
                        .HasColumnType("numeric");

                    b.Property<Guid>("CompraPartidaId")
                        .HasColumnType("uuid");

                    b.Property<int>("NumAlm")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CompraPartidaId");

                    b.ToTable("CompraPartidasAlmacen");
                });

            modelBuilder.Entity("Comssire.Models.Compras.MovimientoInventario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("numeric");

                    b.Property<Guid>("CompraId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("CostoUnitario")
                        .HasColumnType("numeric");

                    b.Property<string>("CveArt")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NumAlm")
                        .HasColumnType("integer");

                    b.Property<string>("Referencia")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("CompraId");

                    b.HasIndex("CveArt", "NumAlm");

                    b.ToTable("MovimientosInventario");
                });

            modelBuilder.Entity("Comssire.Models.FbProveedor", b =>
                {
                    b.Property<string>("Clave")
                        .HasColumnType("text");

                    b.Property<string>("Banco")
                        .HasColumnType("text");

                    b.Property<string>("Calle")
                        .HasColumnType("text");

                    b.Property<string>("Clasific")
                        .HasColumnType("text");

                    b.Property<int?>("Codigo")
                        .HasColumnType("integer");

                    b.Property<string>("Colonia")
                        .HasColumnType("text");

                    b.Property<string>("ConCredito")
                        .HasColumnType("text");

                    b.Property<string>("Cruzamientos")
                        .HasColumnType("text");

                    b.Property<string>("Cruzamientos2")
                        .HasColumnType("text");

                    b.Property<string>("CuentaContable")
                        .HasColumnType("text");

                    b.Property<int?>("CveObs")
                        .HasColumnType("integer");

                    b.Property<string>("CvePais")
                        .HasColumnType("text");

                    b.Property<string>("DescOtros")
                        .HasColumnType("text");

                    b.Property<decimal?>("Descuento")
                        .HasColumnType("numeric(18,6)");

                    b.Property<int?>("DiasCred")
                        .HasColumnType("integer");

                    b.Property<string>("Emailpred")
                        .HasColumnType("text");

                    b.Property<string>("Enviosilen")
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .HasColumnType("text");

                    b.Property<string>("FormaPago")
                        .HasColumnType("text");

                    b.Property<string>("Imprir")
                        .HasColumnType("text");

                    b.Property<decimal?>("Lat")
                        .HasColumnType("numeric(18,6)");

                    b.Property<decimal?>("LimCred")
                        .HasColumnType("numeric(18,6)");

                    b.Property<string>("Localidad")
                        .HasColumnType("text");

                    b.Property<decimal?>("Lon")
                        .HasColumnType("numeric(18,6)");

                    b.Property<string>("Mail")
                        .HasColumnType("text");

                    b.Property<string>("Municipio")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .HasColumnType("text");

                    b.Property<string>("NumExt")
                        .HasColumnType("text");

                    b.Property<int?>("NumInt")
                        .HasColumnType("integer");

                    b.Property<string>("Rfc")
                        .HasColumnType("text");

                    b.Property<decimal?>("Saldo")
                        .HasColumnType("numeric(18,6)");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.Property<int?>("TipOpera")
                        .HasColumnType("integer");

                    b.Property<int?>("TipTercero")
                        .HasColumnType("integer");

                    b.Property<int?>("UltCompD")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UltCompF")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal?>("UltCompM")
                        .HasColumnType("numeric(18,6)");

                    b.Property<string>("UltPagoD")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UltPagoF")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal?>("UltPagoM")
                        .HasColumnType("numeric(18,6)");

                    b.Property<decimal?>("Ventas")
                        .HasColumnType("numeric(18,6)");

                    b.HasKey("Clave");

                    b.HasIndex("Nombre");

                    b.ToTable("fb_proveedores");
                });

            modelBuilder.Entity("Comssire.Models.Firebird.FbAlmacen", b =>
                {
                    b.Property<int>("CveAlm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CveAlm"));

                    b.Property<int?>("CveMent")
                        .HasColumnType("integer");

                    b.Property<int?>("CveMsal")
                        .HasColumnType("integer");

                    b.Property<string>("Descr")
                        .HasColumnType("text");

                    b.Property<string>("Direccion")
                        .HasColumnType("text");

                    b.Property<string>("Encargado")
                        .HasColumnType("text");

                    b.Property<decimal?>("Lat")
                        .HasColumnType("numeric(18,6)");

                    b.Property<decimal?>("ListaPrec")
                        .HasColumnType("numeric(18,6)");

                    b.Property<decimal?>("Lon")
                        .HasColumnType("numeric(18,6)");

                    b.Property<string>("Status")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.Property<string>("UbiDest")
                        .HasColumnType("text");

                    b.Property<string>("Uuid")
                        .HasColumnType("text");

                    b.Property<DateTime?>("VersionSinc")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("CveAlm");

                    b.ToTable("fb_almacenes");
                });

            modelBuilder.Entity("Comssire.Models.Firebird.FbExistenciaAlmacen", b =>
                {
                    b.Property<string>("CveArt")
                        .HasColumnType("text");

                    b.Property<int>("CveAlm")
                        .HasColumnType("integer");

                    b.Property<int?>("CompXRec")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Exist")
                        .HasColumnType("numeric(18,6)");

                    b.Property<decimal?>("PendSurt")
                        .HasColumnType("numeric(18,6)");

                    b.Property<string>("Status")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<decimal?>("StockMax")
                        .HasColumnType("numeric(18,6)");

                    b.Property<decimal?>("StockMin")
                        .HasColumnType("numeric(18,6)");

                    b.Property<string>("Uuid")
                        .HasColumnType("text");

                    b.Property<DateTime?>("VersionSinc")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("CveArt", "CveAlm");

                    b.ToTable("fb_existencias_almacen");
                });

            modelBuilder.Entity("Comssire.Models.Firebird.FbProducto", b =>
                {
                    b.Property<string>("CveArt")
                        .HasColumnType("text");

                    b.Property<decimal?>("AltoMl")
                        .HasColumnType("numeric(18,6)");

                    b.Property<decimal?>("AnchoMl")
                        .HasColumnType("numeric(18,6)");

                    b.Property<int?>("Apart")
                        .HasColumnType("integer");

                    b.Property<string>("AplManIeps")
                        .HasColumnType("text");

                    b.Property<int?>("AplManImp")
                        .HasColumnType("integer");

                    b.Property<string>("BlkCstExt")
                        .HasColumnType("text");

                    b.Property<decimal?>("CompAnlC")
                        .HasColumnType("numeric(18,6)");

                    b.Property<decimal?>("CompAnlM")
                        .HasColumnType("numeric(18,6)");

                    b.Property<int?>("CompXRec")
                        .HasColumnType("integer");

                    b.Property<string>("ConLote")
                        .HasColumnType("text");

                    b.Property<string>("ConPedimento")
                        .HasColumnType("text");

                    b.Property<string>("ConSerie")
                        .HasColumnType("text");

                    b.Property<decimal?>("CostoProm")
                        .HasColumnType("numeric(18,6)");

                    b.Property<string>("CtrlAlm")
                        .HasColumnType("text");

                    b.Property<string>("CuentCont")
                        .HasColumnType("text");

                    b.Property<decimal?>("CuotaIeps")
                        .HasColumnType("numeric(18,6)");

                    b.Property<int?>("CveEsqImpu")
                        .HasColumnType("integer");

                    b.Property<int?>("CveObs")
                        .HasColumnType("integer");

                    b.Property<string>("CveProdserv")
                        .HasColumnType("text");

                    b.Property<string>("CveUnidad")
                        .HasColumnType("text");

                    b.Property<string>("Descr")
                        .HasColumnType("text");

                    b.Property<decimal?>("Exist")
                        .HasColumnType("numeric(18,6)");

                    b.Property<decimal?>("FacConv")
                        .HasColumnType("numeric(18,6)");

                    b.Property<decimal?>("FacUnidCce")
                        .HasColumnType("numeric(18,6)");

                    b.Property<DateTime?>("FchUltCom")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("FchUltVta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal?>("LargoMl")
                        .HasColumnType("numeric(18,6)");

                    b.Property<string>("LinProd")
                        .HasColumnType("text");

                    b.Property<string>("ManIeps")
                        .HasColumnType("text");

                    b.Property<int?>("NumMon")
                        .HasColumnType("integer");

                    b.Property<decimal?>("PendSurt")
                        .HasColumnType("numeric(18,6)");

                    b.Property<decimal?>("Peso")
                        .HasColumnType("numeric(18,6)");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<decimal?>("StockMax")
                        .HasColumnType("numeric(18,6)");

                    b.Property<decimal?>("StockMin")
                        .HasColumnType("numeric(18,6)");

                    b.Property<int?>("TiemSurt")
                        .HasColumnType("integer");

                    b.Property<string>("TipCosteo")
                        .HasColumnType("text");

                    b.Property<string>("TipoEle")
                        .HasColumnType("text");

                    b.Property<decimal?>("UltCosto")
                        .HasColumnType("numeric(18,6)");

                    b.Property<string>("UniAlt")
                        .HasColumnType("text");

                    b.Property<int?>("UniEmp")
                        .HasColumnType("integer");

                    b.Property<string>("UniMed")
                        .HasColumnType("text");

                    b.Property<string>("Uuid")
                        .HasColumnType("text");

                    b.Property<DateTime?>("VersionSinc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("VersionSincFechaImg")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal?>("Volumen")
                        .HasColumnType("numeric(18,6)");

                    b.Property<decimal?>("VtasAnlC")
                        .HasColumnType("numeric(18,6)");

                    b.Property<decimal?>("VtasAnlM")
                        .HasColumnType("numeric(18,6)");

                    b.HasKey("CveArt");

                    b.HasIndex("Descr");

                    b.ToTable("fb_productos");
                });

            modelBuilder.Entity("Comssire.Models.Sistema.Permiso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Clave")
                        .IsUnique();

                    b.ToTable("Permisos");
                });

            modelBuilder.Entity("Comssire.Models.Sistema.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Comssire.Models.Sistema.RolPermiso", b =>
                {
                    b.Property<int>("RolId")
                        .HasColumnType("integer");

                    b.Property<int>("PermisoId")
                        .HasColumnType("integer");

                    b.HasKey("RolId", "PermisoId");

                    b.HasIndex("PermisoId");

                    b.ToTable("RolesPermisos");
                });

            modelBuilder.Entity("Comssire.Models.Sistema.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RolId")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RolId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Comssire.Models.Compras.Compra", b =>
                {
                    b.HasOne("Comssire.Models.Sistema.Usuario", "AprobadoPor")
                        .WithMany()
                        .HasForeignKey("AprobadoPorUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Comssire.Models.Sistema.Usuario", "CreadoPor")
                        .WithMany()
                        .HasForeignKey("CreadoPorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Comssire.Models.Sistema.Usuario", "EnviadoPor")
                        .WithMany()
                        .HasForeignKey("EnviadoPorUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Comssire.Models.Sistema.Usuario", "RechazadoPor")
                        .WithMany()
                        .HasForeignKey("RechazadoPorUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AprobadoPor");

                    b.Navigation("CreadoPor");

                    b.Navigation("EnviadoPor");

                    b.Navigation("RechazadoPor");
                });

            modelBuilder.Entity("Comssire.Models.Compras.CompraPartida", b =>
                {
                    b.HasOne("Comssire.Models.Compras.Compra", "Compra")
                        .WithMany("Partidas")
                        .HasForeignKey("CompraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Compra");
                });

            modelBuilder.Entity("Comssire.Models.Compras.CompraPartidaAlmacen", b =>
                {
                    b.HasOne("Comssire.Models.Compras.CompraPartida", "Partida")
                        .WithMany("Repartos")
                        .HasForeignKey("CompraPartidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partida");
                });

            modelBuilder.Entity("Comssire.Models.Sistema.RolPermiso", b =>
                {
                    b.HasOne("Comssire.Models.Sistema.Permiso", "Permiso")
                        .WithMany("RolesPermisos")
                        .HasForeignKey("PermisoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Comssire.Models.Sistema.Rol", "Rol")
                        .WithMany("RolesPermisos")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permiso");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Comssire.Models.Sistema.Usuario", b =>
                {
                    b.HasOne("Comssire.Models.Sistema.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Comssire.Models.Compras.Compra", b =>
                {
                    b.Navigation("Partidas");
                });

            modelBuilder.Entity("Comssire.Models.Compras.CompraPartida", b =>
                {
                    b.Navigation("Repartos");
                });

            modelBuilder.Entity("Comssire.Models.Sistema.Permiso", b =>
                {
                    b.Navigation("RolesPermisos");
                });

            modelBuilder.Entity("Comssire.Models.Sistema.Rol", b =>
                {
                    b.Navigation("RolesPermisos");

                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
