// <auto-generated />
using System;
using Comssire.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Comssire.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260202214146_FixTextColumns")]
    partial class FixTextColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Comssire.Models.FbProveedor", b =>
                {
                    b.Property<string>("Clave")
                        .HasColumnType("text");

                    b.Property<string>("Banco")
                        .HasColumnType("text");

                    b.Property<string>("Calle")
                        .HasColumnType("text");

                    b.Property<string>("Clasific")
                        .HasColumnType("text");

                    b.Property<int?>("Codigo")
                        .HasColumnType("integer");

                    b.Property<string>("Colonia")
                        .HasColumnType("text");

                    b.Property<string>("ConCredito")
                        .HasColumnType("text");

                    b.Property<string>("Cruzamientos")
                        .HasColumnType("text");

                    b.Property<string>("Cruzamientos2")
                        .HasColumnType("text");

                    b.Property<string>("CuentaContable")
                        .HasColumnType("text");

                    b.Property<int?>("CveObs")
                        .HasColumnType("integer");

                    b.Property<string>("CvePais")
                        .HasColumnType("text");

                    b.Property<string>("DescOtros")
                        .HasColumnType("text");

                    b.Property<decimal?>("Descuento")
                        .HasColumnType("numeric(18,6)");

                    b.Property<int?>("DiasCred")
                        .HasColumnType("integer");

                    b.Property<string>("Emailpred")
                        .HasColumnType("text");

                    b.Property<string>("Enviosilen")
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .HasColumnType("text");

                    b.Property<string>("FormaPago")
                        .HasColumnType("text");

                    b.Property<string>("Imprir")
                        .HasColumnType("text");

                    b.Property<decimal?>("Lat")
                        .HasColumnType("numeric(18,6)");

                    b.Property<decimal?>("LimCred")
                        .HasColumnType("numeric(18,6)");

                    b.Property<string>("Localidad")
                        .HasColumnType("text");

                    b.Property<decimal?>("Lon")
                        .HasColumnType("numeric(18,6)");

                    b.Property<string>("Mail")
                        .HasColumnType("text");

                    b.Property<string>("Municipio")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .HasColumnType("text");

                    b.Property<string>("NumExt")
                        .HasColumnType("text");

                    b.Property<int?>("NumInt")
                        .HasColumnType("integer");

                    b.Property<string>("Rfc")
                        .HasColumnType("text");

                    b.Property<decimal?>("Saldo")
                        .HasColumnType("numeric(18,6)");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.Property<int?>("TipOpera")
                        .HasColumnType("integer");

                    b.Property<int?>("TipTercero")
                        .HasColumnType("integer");

                    b.Property<int?>("UltCompD")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UltCompF")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal?>("UltCompM")
                        .HasColumnType("numeric(18,6)");

                    b.Property<string>("UltPagoD")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UltPagoF")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal?>("UltPagoM")
                        .HasColumnType("numeric(18,6)");

                    b.Property<decimal?>("Ventas")
                        .HasColumnType("numeric(18,6)");

                    b.HasKey("Clave");

                    b.HasIndex("Nombre");

                    b.ToTable("fb_proveedores");
                });

            modelBuilder.Entity("Comssire.Models.Firebird.FbAlmacen", b =>
                {
                    b.Property<int>("CveAlm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CveAlm"));

                    b.Property<int?>("CveMent")
                        .HasColumnType("integer");

                    b.Property<int?>("CveMsal")
                        .HasColumnType("integer");

                    b.Property<string>("Descr")
                        .HasColumnType("text");

                    b.Property<string>("Direccion")
                        .HasColumnType("text");

                    b.Property<string>("Encargado")
                        .HasColumnType("text");

                    b.Property<decimal?>("Lat")
                        .HasColumnType("numeric(18,6)");

                    b.Property<decimal?>("ListaPrec")
                        .HasColumnType("numeric(18,6)");

                    b.Property<decimal?>("Lon")
                        .HasColumnType("numeric(18,6)");

                    b.Property<string>("Status")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.Property<string>("UbiDest")
                        .HasColumnType("text");

                    b.Property<string>("Uuid")
                        .HasColumnType("text");

                    b.Property<DateTime?>("VersionSinc")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("CveAlm");

                    b.ToTable("fb_almacenes");
                });

            modelBuilder.Entity("Comssire.Models.Firebird.FbExistenciaAlmacen", b =>
                {
                    b.Property<string>("CveArt")
                        .HasColumnType("text");

                    b.Property<int>("CveAlm")
                        .HasColumnType("integer");

                    b.Property<int?>("CompXRec")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Exist")
                        .HasColumnType("numeric(18,6)");

                    b.Property<decimal?>("PendSurt")
                        .HasColumnType("numeric(18,6)");

                    b.Property<string>("Status")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<decimal?>("StockMax")
                        .HasColumnType("numeric(18,6)");

                    b.Property<decimal?>("StockMin")
                        .HasColumnType("numeric(18,6)");

                    b.Property<string>("Uuid")
                        .HasColumnType("text");

                    b.Property<DateTime?>("VersionSinc")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("CveArt", "CveAlm");

                    b.ToTable("fb_existencias_almacen");
                });

            modelBuilder.Entity("Comssire.Models.Firebird.FbProducto", b =>
                {
                    b.Property<string>("CveArt")
                        .HasColumnType("text");

                    b.Property<decimal?>("AltoMl")
                        .HasColumnType("numeric(18,6)");

                    b.Property<decimal?>("AnchoMl")
                        .HasColumnType("numeric(18,6)");

                    b.Property<int?>("Apart")
                        .HasColumnType("integer");

                    b.Property<string>("AplManIeps")
                        .HasColumnType("text");

                    b.Property<int?>("AplManImp")
                        .HasColumnType("integer");

                    b.Property<string>("BlkCstExt")
                        .HasColumnType("text");

                    b.Property<decimal?>("CompAnlC")
                        .HasColumnType("numeric(18,6)");

                    b.Property<decimal?>("CompAnlM")
                        .HasColumnType("numeric(18,6)");

                    b.Property<int?>("CompXRec")
                        .HasColumnType("integer");

                    b.Property<string>("ConLote")
                        .HasColumnType("text");

                    b.Property<string>("ConPedimento")
                        .HasColumnType("text");

                    b.Property<string>("ConSerie")
                        .HasColumnType("text");

                    b.Property<decimal?>("CostoProm")
                        .HasColumnType("numeric(18,6)");

                    b.Property<string>("CtrlAlm")
                        .HasColumnType("text");

                    b.Property<string>("CuentCont")
                        .HasColumnType("text");

                    b.Property<decimal?>("CuotaIeps")
                        .HasColumnType("numeric(18,6)");

                    b.Property<int?>("CveEsqImpu")
                        .HasColumnType("integer");

                    b.Property<int?>("CveObs")
                        .HasColumnType("integer");

                    b.Property<string>("CveProdserv")
                        .HasColumnType("text");

                    b.Property<string>("CveUnidad")
                        .HasColumnType("text");

                    b.Property<string>("Descr")
                        .HasColumnType("text");

                    b.Property<decimal?>("Exist")
                        .HasColumnType("numeric(18,6)");

                    b.Property<decimal?>("FacConv")
                        .HasColumnType("numeric(18,6)");

                    b.Property<decimal?>("FacUnidCce")
                        .HasColumnType("numeric(18,6)");

                    b.Property<DateTime?>("FchUltCom")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("FchUltVta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal?>("LargoMl")
                        .HasColumnType("numeric(18,6)");

                    b.Property<string>("LinProd")
                        .HasColumnType("text");

                    b.Property<string>("ManIeps")
                        .HasColumnType("text");

                    b.Property<int?>("NumMon")
                        .HasColumnType("integer");

                    b.Property<decimal?>("PendSurt")
                        .HasColumnType("numeric(18,6)");

                    b.Property<decimal?>("Peso")
                        .HasColumnType("numeric(18,6)");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<decimal?>("StockMax")
                        .HasColumnType("numeric(18,6)");

                    b.Property<decimal?>("StockMin")
                        .HasColumnType("numeric(18,6)");

                    b.Property<int?>("TiemSurt")
                        .HasColumnType("integer");

                    b.Property<string>("TipCosteo")
                        .HasColumnType("text");

                    b.Property<string>("TipoEle")
                        .HasColumnType("text");

                    b.Property<decimal?>("UltCosto")
                        .HasColumnType("numeric(18,6)");

                    b.Property<string>("UniAlt")
                        .HasColumnType("text");

                    b.Property<int?>("UniEmp")
                        .HasColumnType("integer");

                    b.Property<string>("UniMed")
                        .HasColumnType("text");

                    b.Property<string>("Uuid")
                        .HasColumnType("text");

                    b.Property<DateTime?>("VersionSinc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("VersionSincFechaImg")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal?>("Volumen")
                        .HasColumnType("numeric(18,6)");

                    b.Property<decimal?>("VtasAnlC")
                        .HasColumnType("numeric(18,6)");

                    b.Property<decimal?>("VtasAnlM")
                        .HasColumnType("numeric(18,6)");

                    b.HasKey("CveArt");

                    b.HasIndex("Descr");

                    b.ToTable("fb_productos");
                });
#pragma warning restore 612, 618
        }
    }
}
